services:
  nats:
    image: "nats:2.10-alpine"
    container_name: asksynk-nats
    ports:
      - "4222:4222"
      - "8222:8222"
  postgres:
    image: "pgvector/pgvector:pg18"
    container_name: asksynk-postgres
    environment:
      POSTGRES_DB: asksynk
      POSTGRES_USER: asksynk
      POSTGRES_PASSWORD: asksynk
    ports:
      - "5432:5432"
    volumes:
      - asksynk-postgres-data:/var/lib/postgresql
      - ./initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U asksynk -d asksynk"]
      interval: 5s
      timeout: 5s
      retries: 10
  mailpit:
    image: "axllent/mailpit:latest"
    container_name: asksynk-mailpit
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  asksynk-postgres-data:
